name : "fortclient-vpn"
description : "Connect to FortiClient VPN"
autor : "JaehaSS"
inputs:
  vpn_ip:
    description: "VPN IP Address"
    required: true
  vpn_port:
    description: "VPN Port"
  vpn_username:
    description: "VPN Username"
    required: true
  vpn_password:
    description: "VPN Password"
    required: true
  
runs:
  using: "docker"
  image : "Dockerfile"
  args:
    - ${{ inputs.vpn_ip }}
    - ${{ inputs.vpn_port }}
    - ${{ inputs.vpn_username }}
    - ${{ inputs.vpn_password }}