name : "fortclient-vpn"
description : "Connect to FortiClient VPN"
autor : "JaehaSS"
inputs:
  VPN_IP:
    description: "VPN IP Address"
    required: true
  VPN_PORT:
    description: "VPN Port"
  VPN_USERNAME:
    description: "VPN Username"
    required: true
  VPN_PASS:
    description: "VPN Password"
    required: true
  

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools ppp libappindicator3-1 expect ca-certificates

    - name: Download and Install FortiClient VPN
      shell: bash
      run: |
        wget https://links.fortinet.com/forticlient/deb/vpnagent -O forticlient.deb
        sudo dpkg -i forticlient.deb
       
    - name: Create VPN Profile
      shell: bash
      run: |
        set -x 
        cat <<EOF > create_vpn_profile.exp
        spawn /opt/forticlient/fortivpn edit myvpn
        expect -re "Remote Gateway:"
        send -- "\$env(INPUT_VPN_IP)\r"
        set timeout -1
        expect -re "Port"
        send -- "\$env(INPUT_VPN_PORT)\r"
        set timeout -1
        expect -re "Authentication"
        send -- "3\r"
        set timeout -1
        expect -re "Certificate"
        send -- "3\r"
        set timeout -1
        expect eof
        EOF
        chmod +x create_vpn_profile.exp
        ./create_vpn_profile.exp
      env:
        INPUT_VPN_IP: ${{ inputs.VPN_IP }}
        INPUT_VPN_PORT: ${{ inputs.VPN_PORT }}

    - name: List VPN Profiles and View Specific Profile
      shell: bash
      run: |
        # List all configured FortiClient VPN profiles
        /opt/forticlient/fortivpn list
        # View the details of the 'myvpn' profile to verify creation
        /opt/forticlient/fortivpn view myvpn

    - name: Create VPN Connect Script and Connect
      shell: bash
      
      run: |
        set -x # Enable debug output
        cat <<EOF > vpnconnect.exp
        #!/usr/bin/expect -f
        
        spawn /opt/forticlient/fortivpn connect myvpn --user=\$env(INPUT_VPN_USERNAME) --password

        expect -exact "password:"
        send -- "\$env(INPUT_VPN_PASS)\r"
        set timeout -1
        expect {
          -re "Confirm " { send -- "y\r"; exp_continue }
          -re "Connected" { exit 0 } 
          eof { exit 1 } 
        }
        expect eof
        EOF
        chmod +x vpnconnect.exp
        ./vpnconnect.exp
      env:
        INPUT_VPN_USERNAME: ${{ inputs.VPN_USERNAME }}
        INPUT_VPN_PASS: ${{ inputs.VPN_PASS }} 
