name : "fortclient-vpn"
description : "Connect to FortiClient VPN"
autor : "JaehaSS"
inputs:
  VPN_IP:
    description: "VPN IP Address"
    required: true
  VPN_PORT:
    description: "VPN Port"
  VPN_USERNAME:
    description: "VPN Username"
    required: true
  VPN_PASS:
    description: "VPN Password"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools ppp libappindicator3-1 expect ca-certificates

    - name: Download and Install FortiClient VPN
      shell: bash

      run: |
        wget https://links.fortinet.com/forticlient/deb/vpnagent -O forticlient.deb
        sudo dpkg -i forticlient.deb

    - name: Create VPN Profile
      shell: bash
      env:
        VPN_IP: ${{ inputs.VPN_IP }}
        VPN_PORT: ${{ inputs.VPN_PORT }}
      run: |
        echo '#!/usr/bin/expect -f' > create_vpn_profile.exp
        echo 'spawn /opt/forticlient/fortivpn edit myvpn' >> create_vpn_profile.exp
        echo 'expect -re "Remote Gateway:"' >> create_vpn_profile.exp
        echo 'send -- "$env(VPN_IP)\r"' >> create_vpn_profile.exp
        echo 'set timeout -1' >> create_vpn_profile.exp
        echo 'expect -re "Port"' >> create_vpn_profile.exp
        echo 'send -- "$env(VPN_PORT)\r"' >> create_vpn_profile.exp
        echo 'set timeout -1' >> create_vpn_profile.exp
        echo 'expect -re "Authentication"' >> create_vpn_profile.exp
        echo 'send -- "3\r"' >> create_vpn_profile.exp
        echo 'set timeout -1' >> create_vpn_profile.exp
        echo 'expect -re "Certificate"' >> create_vpn_profile.exp
        echo 'send -- "3\r"' >> create_vpn_profile.exp
        echo 'set timeout -1' >> create_vpn_profile.exp
        echo 'expect eof' >> create_vpn_profile.exp
        chmod +x create_vpn_profile.exp
        ./create_vpn_profile.exp
          
    - name: List VPN Script
      shell: bash
      run: |
        /opt/forticlient/fortivpn list
        /opt/forticlient/fortivpn view myvpn

    - name: Create VPN Connect Script
      shell: bash
      run: |
        set -x
        echo '#!/usr/bin/expect -f' > vpnconnect.exp
        echo 'spawn /opt/forticlient/fortivpn connect myvpn --user=$env(VPN_USERNAME) --password' >> vpnconnect.exp
        echo 'expect -exact "Password:"' >> vpnconnect.exp
        echo 'send -- "$env(VPN_PASS)\r"' >> vpnconnect.exp 
        echo 'set timeout 30' >> vpnconnect.exp
        echo 'expect -re "Confirm "' >> vpnconnect.exp
        echo 'send -- "y\r"' >> vpnconnect.exp
        echo 'set timeout 30' >> vpnconnect.exp
        echo 'expect eof' >> vpnconnect.exp
        chmod +x vpnconnect.exp

    - name : Connect to VPN
      shell: bash
      env:
        VPN_USERNAME: ${{ inputs.VPN_USERNAME }}
        VPN_PASS: ${{ inputs.VPN_PASS }}
      run: |
        MAX_RETRIES=5
        TIMEOUT_SECONDS=10
        RETRY_DELAY=5
        
        for ((i=1; i<=MAX_RETRIES; i++)); do
          echo "[$i/$MAX_RETRIES] VPN 연결 시도 중..."
        
          timeout $TIMEOUT_SECONDS ./vpnconnect.exp
          STATUS=$?
        
          if [ $STATUS -eq 0 ]; then
            echo "VPN 연결 성공!"
            exit 0
          else
            echo "VPN 연결 실패 또는 타임아웃 (code: $STATUS)"
            if [ $i -lt $MAX_RETRIES ]; then
              echo "재시도까지 ${RETRY_DELAY}초 대기..."
              sleep $RETRY_DELAY
            fi
          fi
        done
        echo "최대 재시도 횟수 초과. 실패 처리."
        exit 1
